### PR TITLE
Update Doomwalker.lua based on testing

### PR DESCRIPTION
**Pull request by Undeadhunter**
Based on following testing:

https://www.youtube.com/watch?v=vDrk_h0_PdM

### CODE REVIEW

**Comment by balleny** [comment]
I know that Taurens and Draenei have a larger model and require an additional +1

So far in all my range adjustments, i have been going with the "default" model size 2 (every race besides gnome(1) and male tauren/dranei(3)), hoping that they would fix the bug sooner than later.

anyway, I would consider also changing the other entries retro-actively - but switched a bit writing the default value + Chromie-specific adjustment for all the timers / ranges to make it easier for others to see the timers or adjust in case of bug fixes

**Comment by balleny** [comment]
oh and sorry for reacting so late but I didnt even got a notification :(

**Comment by balleny** [comment]
did you by any chance also test the range for jumps other than size 3 to size 3, but e.g. size 3 to size 2?

**Comment by Undeadhunter** [comment]
https://www.youtube.com/watch?v=q2wM4Gq2lBs 

Human Male + Blood Elf Female, also 13

**Comment by balleny** [comment]
hm interesting but okay, i will adopt it soon. have to see if I make another release before Karazhan or not
thanks for the input!

**Comment by balleny** [comment]
Thanks for the feedback again,
i implemented the change here https://github.com/balleny/DBM/commit/06ac470a77535916847193d1c26ec9bc0f49abd1

feel free to msg me also directly in discord

**Pull request closed without merging**
